version: "3"
networks:
  default:
    name: eil

services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdfasdf
      POSTGRES_DB: crowdrocks
    ports:
      - 5432:5432

  api:
    image: etenlab/crowd-rocks:dev
    environment:
      CR_DB_URL: postgres
      CR_DB_PORT: 5432
      CR_DB_USER: postgres
      CR_DB_PASSWORD: asdfasdf
      CR_DB: crowdrocks
      ADMIN_PASSWORD: asdfasdf
      MODE: DEV
      PORT: 80
    ports:
      - 3000:80
    depends_on:
      - postgres
