# AWS env settings
awsAccountId: '605254017010'
awsRegion: 'us-east-2'

# Prefix used to identify app CloudFormation component
appPrefix: 'cb'

# VPC configuration
vpcCidr: '10.10.0.0/16'
natGatewaysCount: 0

# Env domain setup
envSubdomain: 'prod'

# App ECS cluster name
ecsClusterName: 'prod-cluster'

# S3 bucket names
publicFilesBucketName: 'crowdrocks-public-files-prod'
tempPublicFilesBucketName: 'crowdrocks-public-files-prod-temp'

# System Manager params to create
vpcSsmParam: '/prod/app-vpc-id'
defaultEcsExecRoleSsmParam: '/prod/ecs-default-execution-role'
defaultEcsTaskRoleSsmParam: '/prod/ecs-default-task-role'
albArnSsmParam: '/prod/alb-arn'
albSecurityGroupSsmParam: '/prod/alb-sg-id'
albListenerSsmParam: '/prod/alb-listener-arn'
dbSecurityGroupSsmParam: '/prod/db-sg-id'

# Secrets Manager params to create
dbCredentialSecret: 'prod/db/credentials'
appSecrets: 'prod/crowdrocksApiServer/secrets'

# Whether database is accessible outside of VPC
dbPublicAccess: true

# DNS setup
dns:
  - existingRootHostedZone: 'crowd.rocks'
    rootDomainCertSsmParam: '/prod/crowd.rocks/root-domain-certificate'

apiService:
  albPort: 3000
  dockerPort: 3000
  priority: 10
  rootdomain: 'crowd.rocks'
  serviceName: 'crowdrocksApiServer'
  dockerImageUrl: 'etenlab/crowd-rocks:latest'
  cpu: 2048
  memory: 4096
  healthCheckPath: '/'
  dbSecrets:
    CR_DB_PASSWORD: password
    CR_DB_USER: username
    CR_DB_URL: host
    CR_DB: dbname
    CR_DB_PORT: port
  appSecrets:
    ADMIN_PASSWORD: ADMIN_PASSWORD
    DEEPL_KEY: DEEPL_KEY
    SMARTCAT_PROFILE: SMARTCAT_PROFILE
    SMARTCAT_KEY: SMARTCAT_KEY
    SMARTCAT_ID: SMARTCAT_ID
    LILT_KEY: LILT_KEY
    GCP_API_KEY: GCP_API_KEY
    GCP_PROJECT_ID: GCP_PROJECT_ID
    OPENAI_API_KEY: OPENAI_API_KEY
    CR_GPT_4_PASSWORD: CR_GPT_4_PASSWORD
    CR_GPT_3_PASSWORD: CR_GPT_3_PASSWORD
    CR_GOOGLE_BOT_PASSWORD: CR_GOOGLE_BOT_PASSWORD

docsApp:
  appId: docs
  domainName: docs.crowd.rocks
  enabled: true
  createCustomDomain: true
