### MEMORIES


GET https://lilt.com/2/memories?key=374e6ccebcac920a894dd33374db253c
Content-Type: application/json
Accept: application/json

### 
POST https://lilt.com/2/memories?key=374e6ccebcac920a894dd33374db253c
Content-Type: application/json
Accept: application/json

{
  "name": "liltbot@crowd.rocks-pl-ru",
  "srclang": "pl",
  "trglang": "ru"
}

###

DELETE https://lilt.com/2/memories?key=374e6ccebcac920a894dd33374db253c&id=109167

"{\"name\":\"liltbot@crowd.rocks-en-uk\",\"srclang\":\"en\",\"trglang\":\"uk\"}"


### FILES
GET https://lilt.com/2/files?key=374e6ccebcac920a894dd33374db253c
Content-Type: application/json
Accept: application/json

###
DELETE  https://lilt.com/2/files?key=374e6ccebcac920a894dd33374db253c&id=4685042
Content-Type: application/json
Accept: application/json


### TRANSLATIONS
GET https://lilt.com/2/translate/files?key=374e6ccebcac920a894dd33374db253c&id=2587089

